version: "3.8"

services:
  db:
    image: postgres:15.0
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: root
    ports:
      - "5432:5432"

# POSTGRES_DB é o mesmo nome do POSTGRES_USER